package com.thoughtworks.codingchallenge.dataobjects;

public enum InputType
{
	INTERGALACTIC_UNITS_IN_ROMAN,
	NO_OF_COMODITY_PRICE_IN_ARABIAN_CREDITS,
	QUESTION_INTERGALACTIC_UNITS_TO_ARABIAN_CREDITS,
	QUESTION_NO_OF_COMODITY_PRICE_IN_ARABIAN_CREDITS,
	INVALID_QUESTION_GRAMMAR,
	INVALID_INPUT_GRAMMAR;
}