package com.thoughtworks.codingchallenge.dataobjects;

public enum InputType
{
	INTERGALACTIC_UNITS_IN_ROMAN,
	GROUPOF_INTERGALACTIC_UNITS_IN_ARABIAN_CREDITS,
	QUESTION_FOR_DECIMAL_PRICE,
	QUESTION_FOR_ARABIAN_CREDITS,
	INVALID_INPUT;
}